### PR TITLE
`PyscfCalculation`: Add support to compute charge density and MEP

### PR DESCRIPTION
**Pull request by sphuber**
The `PyscfCalculation` is updated to allow specifying the `density` and
`mep` keys in the `parameters` input, in which case the charge density
and molecular electrostatic potential are computed and attached as
`SinglefileData` nodes in `.cube` format.

### CODE REVIEW

**Comment by adam-grofe** [comment]
Yea, this is a lot better. However, MSR showed me a faster way to implement the MEP. I didn't get time to implement their solution into the plugin yet though. I will look back at that thread and modify the branch here.

**Comment by sphuber** [comment]
@adam-grofe I have added your commit, but I left out the env.yml and notebook. There are already examples in the `README.md`. We can integrate this example notebook with the `aiida-pyscf` tile in `aiida-azq` though and show the calculation and visualization of the density and MEP.

I have also added some more comments for clarification to your implementation in the cubegen template. Could you have a quick look at my last commit and confirm if things are correct. If so, we can merge this and make a new release.

**Comment by adam-grofe** [comment]
It looks good to me.

**Comment by sphuber** [comment]
Thanks @adam-grofe !

**Pull request merged**
